apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: marshaller
spec:
  schedule: "55 0/1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: apply-data
            image: tombatchelor/daily_tasks:6.2
            imagePullPolicy: Always
            env:
            - name: COLLECTOR_URL
              valueFrom:
                configMapKeyRef:
                  name: marshaller
                  key: collector.url
            - name: CUSTOMER_ID
              valueFrom:
                configMapKeyRef:
                  name: marshaller
                  key: customer.id
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: observe-key
                  key: token
            - name: GIT_ROOT
              valueFrom:
                configMapKeyRef:
                  name: jenkins-env
                  key: git.root
            volumeMounts:
            - name: git-key
              mountPath: /keys
          restartPolicy: OnFailure
          
          volumes:
          - name: git-key
            secret:
              secretName: git-key
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: bad-config
spec:
  schedule: "17 4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: bad-config
          containers:
          - name: apply-data
            image: tombatchelor/config_change:6.0
            imagePullPolicy: Always
            env:
            - name: MODE
              value: BAD
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: config-automation
spec:
  schedule: "43 8 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: config-automation
          containers:
          - name: apply-data
            image: tombatchelor/config_change:6.0
            imagePullPolicy: Always
            env:
            - name: MODE
              value: GOOD
          restartPolicy: OnFailure
